# Generated by Django 2.0.7 on 2018-07-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_key', models.CharField(max_length=20)),
                ('header_value', models.CharField(max_length=400)),
                ('body_content_type', models.SmallIntegerField(choices=[(0, 'x-www-form-urlencoded'), (1, 'json')])),
                ('body_key', models.CharField(max_length=20)),
                ('body_value', models.CharField(max_length=400)),
                ('response_value', models.CharField(max_length=400)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Api')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Project')),
            ],
        ),
    ]
