# Generated by Django 2.0.7 on 2018-08-04 13:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_del', models.SmallIntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='author_manage.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.SmallIntegerField(choices=[(0, '产品经理'), (1, '开发'), (2, '测试'), (3, '运维')])),
                ('status', models.SmallIntegerField(choices=[(0, '离职'), (1, '在职')], default=1)),
                ('is_del', models.SmallIntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1)),
                ('password', models.CharField(max_length=128)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_manage.Organization')),
            ],
        ),
    ]
