# Generated by Django 2.0.7 on 2018-08-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manage', '0006_auto_20180804_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(choices=[(0, '跳过'), (1, '启用')], default=1)),
                ('desc', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'running'), (1, 'finish')], null=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=1)),
                ('headers', models.TextField(default='NULL')),
                ('body', models.TextField(default='NULL')),
                ('check', models.TextField(default='NULL')),
                ('is_del', models.SmallIntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Api')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('case', models.ManyToManyField(to='ceshi_manage.Case')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Environment')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Task'),
        ),
    ]
