# Generated by Django 2.0.7 on 2018-07-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(choices=[(0, '跳过'), (1, '启用')], default=1)),
                ('desc', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'herader value'), (2, 'body value')])),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=1)),
                ('para_type', models.SmallIntegerField(choices=[(10, 'herader para'), (21, 'body para urlencoded'), (22, 'body para json')])),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=400)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Api')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Case')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('case', models.ManyToManyField(to='ceshi_manage.Case')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Environment')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ManyToManyField(to='ceshi_manage.Task'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Step'),
        ),
    ]
