# Generated by Django 2.0.7 on 2018-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='key',
        ),
        migrations.RemoveField(
            model_name='step',
            name='para',
        ),
        migrations.RemoveField(
            model_name='step',
            name='para_type',
        ),
        migrations.RemoveField(
            model_name='step',
            name='value',
        ),
        migrations.AddField(
            model_name='step',
            name='body',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='step',
            name='headers',
            field=models.TextField(default='NULL'),
        ),
    ]
