# Generated by Django 2.0.7 on 2018-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, '运行中'), (1, '结束')], null=True),
        ),
    ]
