# Generated by Django 2.0.7 on 2018-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi_manage', '0002_auto_20180821_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.FloatField(unique=True),
        ),
    ]
