# Generated by Django 2.0.7 on 2018-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi_manage', '0002_auto_20180814_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='check',
            field=models.TextField(default='NULL'),
        ),
        migrations.DeleteModel(
            name='CheckPoint',
        ),
    ]
