# Generated by Django 2.0.7 on 2018-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi_manage', '0003_auto_20180814_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_del',
            field=models.SmallIntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1),
        ),
    ]
