# Generated by Django 2.0.7 on 2018-08-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0007_auto_20180828_2237'),
        ('ceshi_manage', '0007_auto_20180828_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Case'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='environment',
        ),
        migrations.AddField(
            model_name='task',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_manage.Environment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='task',
            name='step',
        ),
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Step'),
            preserve_default=False,
        ),
    ]
