# Generated by Django 2.0.7 on 2018-08-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0007_auto_20180828_2237'),
        ('ceshi_manage', '0008_auto_20180829_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Case')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manage.Environment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Step')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.RemoveField(
            model_name='task',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='step',
        ),
        migrations.AddField(
            model_name='taskenvironment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceshi_manage.Task'),
        ),
    ]
