# Generated by Django 2.0.7 on 2018-08-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='desc',
            new_name='describe',
        ),
    ]
