# Generated by Django 2.0.7 on 2018-08-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0002_auto_20180804_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='describe',
            new_name='note',
        ),
    ]
