# Generated by Django 2.0.7 on 2018-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0002_remove_environment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='name',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='environment',
            name='host',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='environment',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '开发环境'), (1, '测试环境'), (2, '准生产环境'), (3, '生产环境')], default='NULL'),
        ),
    ]
