# Generated by Django 2.0.7 on 2018-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0003_auto_20180730_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '开发环境'), (1, '测试环境'), (2, '准生产环境'), (3, '生产环境')]),
        ),
    ]
