# Generated by Django 2.0.7 on 2018-08-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0003_auto_20180804_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='note',
            new_name='aaa',
        ),
    ]
