# Generated by Django 2.0.7 on 2018-08-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0004_auto_20180804_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='aaa',
            new_name='desc',
        ),
    ]
