# Generated by Django 2.0.7 on 2018-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manage', '0005_auto_20180804_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='path',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
